### ISSUE TITLE
Trait `Interpolate<f64>` not implemented for `Matrix<f64, Const<3>, Const<1>, ArrayStorage<f64, 3, 1>>`

### ISSUE THREAD

**Issue by timtro** [qhdwight/mpc-rs#1]
Cloning and compiling under Ubuntu with rustc 1.78.0 (9b00956e5 2024-04-29) leads to a trait bound violation:

```
   Compiling mpc-rs v0.1.0 (/home/timtro/rustl/mpc-rs)
error[E0277]: the trait bound `Matrix<f64, Const<3>, Const<1>, ArrayStorage<f64, 3, 1>>: Interpolate<f64>` is not satisfied
   --> src/controller.rs:159:34
    |
159 | ...        .map(|i| self.spline.clamped_sample(t + i as f64 * self.dt).expect("Failed to sa...
    |                                 ^^^^^^^^^^^^^^ the trait `Interpolate<f64>` is not implemented for `Matrix<f64, Const<3>, Const<1>, ArrayStorage<f64, 3, 1>>`
    |
    = help: the following other types implement trait `Interpolate<T>`:
              <f32 as Interpolate<f32>>
              <f64 as Interpolate<f32>>
              <f64 as Interpolate<f64>>
              <nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::Const<1>, nalgebra::base::dimension::Const<1>, nalgebra::base::array_storage::ArrayStorage<f32, 1, 1>> as Interpolate<f32>>
              <nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::Const<2>, nalgebra::base::dimension::Const<1>, nalgebra::base::array_storage::ArrayStorage<f32, 2, 1>> as Interpolate<f32>>
              <nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::Const<3>, nalgebra::base::dimension::Const<1>, nalgebra::base::array_storage::ArrayStorage<f32, 3, 1>> as Interpolate<f32>>
              <nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::Const<4>, nalgebra::base::dimension::Const<1>, nalgebra::base::array_storage::ArrayStorage<f32, 4, 1>> as Interpolate<f32>>
              <nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::Const<5>, nalgebra::base::dimension::Const<1>, nalgebra::base::array_storage::ArrayStorage<f32, 5, 1>> as Interpolate<f32>>
            and 9 others
note: required by a bound in `Spline::<T, V>::clamped_sample`
   --> /home/timtro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/splines-4.3.1/src/spline.rs:248:8
    |
245 |   pub fn clamped_sample(&self, t: T) -> Option<V>
    |          -------------- required by a bound in this associated function
...
248 |     V: Interpolate<T>,
    |        ^^^^^^^^^^^^^^ required by this bound in `Spline::<T, V>::clamped_sample`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `mpc-rs` (lib) due to 1 previous error
```

I'm just learning Rust, so I haven't put together a fix/PR yet.

I see that in `Cargo.toml` you have selected the 'naglebra' feature of the splines crate, so I'm not sure what's going wrong. But happy to help, given some direction.

I'll keep chipping away until I can be useful.

**Comment by qhdwight** [comment]
Hey, I'll take a look. The only thing that should have changed from my setup to yours is the compiler version.

I will probably upgrade the whole thing, let me see how long it will take. The Bevy version is pretty old.

**Comment by qhdwight** [comment]
Try the `main` branch now, works for me with `rustc 1.78.0 (9b00956e5 2024-04-29)` on my M1

**Comment by qhdwight** [comment]
Also be warned I'm not exactly sure if this implementation of MPC is 100% correct. There is some odd behavior with the bot I intended to figure out at some point and never got to it.

**Comment by qhdwight** [comment]
hmm ok this doesn't compile on Windows. could this be a rustc bug?

**Comment by timtro** [comment]
> Also be warned I'm not exactly sure if this implementation of MPC is 100% correct. There is some odd behavior with the bot I intended to figure out at some point and never got to it.

Thanks for the warning. I'm a control systems software engineer/computational physicist/systems theorist, learning Rust. I'm using your lovely project as a starting point (thank you, by the way) as a learning tool. I'm a C++ guy, so jumping into a code base with visualisation and linear algebra libraries all chosen and demonstrated is a huge help. But I'll be slowly rewriting everything to replicate the behaviour of my existing C++ tooling.

If you'd like, when I rewrite the MPC code, I'll happily contribute it back.

**Comment by timtro** [comment]
> Try the `main` branch now, works for me with `rustc 1.78.0 (9b00956e5 2024-04-29)` on my M1

Now works for me too! Good work! Thanks! I'll look at the diffs tomorrow.

As for Windows: I don't have a windows machine to test on. I'm the noob here so your guess is far better than mine. What's the error message you're seeing? The usual suspect with these sorts of cross-platform things is the GUI. It's usually a non-equivalence where some bit of code forks: if *nix, do this, if Windows, do that. So could it be Bevy?

**Comment by timtro** [comment]
Commit a6361ca fixes the issue for me. It now compiles and I am able to run the `robot` example, which produces output as per the animation in the README.

Thank you, @qhdwight. Let me know if you'd be open to accepting PRs for tweaks to the MPC algo. I do see from the robot's behaviour that something is off. Eg, It travels parallel to the line segments of the path, where I would expect quadratic error penalty to drive convergence behaviour where steering input turns the robot toward the path segments.

**Comment by qhdwight** [comment]
> Let me know if you'd be open to accepting PRs for tweaks to the MPC algo. 

Definitely! This repo was my first attempt at MPC so it is a bit rough.
